# This is a comment

# application is mandatory
application: stringupper

# version is mandatory
version: 1-1

# runtime is mandatory
runtime: go

# api_version is mandatory
api_version: go1

# handlers is mandatory
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# All URLs beginning with /css are treated as paths to static files in
# the css/ directory.
- url: /css
  static_dir: css
  
- url: /.*
  script: _go_app

  